image: ubuntu:18.04

before_script:
  - apt-get update
  # below is to install .NET SDK, taken from https://www.microsoft.com/net/download/linux-package-manager/ubuntu18-04/sdk-current
  - apt install -y wget
  - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
  - dpkg -i packages-microsoft-prod.deb
  - apt install -y apt-transport-https
  - apt update
  - apt install -y dotnet-sdk-2.1

stages:
  - build
  - test

build:
  stage: build
  script:
    - time (dotnet build)

test:
  stage: test
  script:
    - time (dotnet build &&
            cd FsharpExchange.Tests/ &&
            dotnet test)

